apiVersion: v1
kind: Deployment
metadata:
  name: static-player-deployment
  namespace: static-player
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        image:
        imagePullPolicy: Always
        name: static-player
        ports:
        - containerPort: 1337
