apiVersion: v1
kind: Service
metadata:
  name: static-player-service
  namespace: static-player
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 1337
    targetPort: 1337
    protocol: TCP
  selector:
    app: static-player
  sessionAffinity: None
